# Logistic Regression using Gradient Descent
The following code implements a logistic regression model with gradient descent using low-level libraries and compares it with a model generated by scikit-learn.

## 1 Data Loading & Cleaning
The data set contains credit card debt information about 10,000 customers and whether they defaulted or not.

In [1]:
# Importing libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
# Loading the data
df = pd.read_csv('Default.csv')
df.head()

  default student      balance        income
0      No      No   729.526495  44361.625074
1      No     Yes   817.180407  12106.134700
2      No      No  1073.549164  31767.138947
3      No      No   529.250605  35704.493935
4      No      No   785.655883  38463.495879

In [3]:
# Scaling and converting to NumPy arrays
df['default']=df['default'].apply(lambda x: 0 if x=='No' else 1)
df['student']=df['student'].apply(lambda x: 0 if x=='No' else 1)

In [4]:
df.head()

   default  student      balance        income
0        0        0   729.526495  44361.625074
1        0        1   817.180407  12106.134700
2        0        0  1073.549164  31767.138947
3        0        0   529.250605  35704.493935
4        0        0   785.655883  38463.495879

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   default  10000 non-null  int64
 1   student  10000 non-null  int64
 2   balance  10000 non-null  float64
 3   income   10000 non-null  float64
dtypes: float64(2), int64(2)
memory usage: 312.6 KB

In [6]:
scaler = StandardScaler()
df[['balance','income']] = scaler.fit_transform(df[['balance','income']])
df

      default  student   balance    income
0           0        0 -0.218835  0.813187
1           0        1 -0.037616 -1.605496
2           0        0  0.492410 -0.131212
3           0        0 -0.632893  0.164031
4           0        0 -0.102791  0.370915
...       ...      ...       ...       ...
9995        0        0 -0.255990  1.460366
9996        0        0 -0.160044 -1.039014
9997        0        0  0.020751  1.883565
9998        0        0  1.516742  0.236363
9999        0        1 -1.311691 -1.248805

[10000 rows x 4 columns]

In [7]:
Y = df['default'].to_numpy().reshape(-1,1)
X = df.drop(columns=['default']).to_numpy()

In [8]:
print("Shape of Y:",Y.shape)
print("Shape of X:",X.shape)

Shape of Y: (10000, 1)
Shape of X: (10000, 3)

In [9]:
X = X.T
Y = Y.T

print("Shape of Y:",Y.shape)
print("Shape of X:",X.shape)

Shape of Y: (1, 10000)
Shape of X: (3, 10000)

## 2 Training a Logistic Regression Model
The following code implements gradient descent to train the logistic regression model.

In [10]:
# Initialising the paramaters of logistic regression
w = np.random.rand(3,1)
b = np.random.rand(1,1)

In [11]:
# Updating parameters using gradient descent
iter = 50000
lr = 0.1
m = Y.shape[1]
for i in np.arange(iter):
    Z = np.dot(w.T,X) + b
    A = 1/(1+np.exp(-Z))
    w = w - lr*(1/m*np.dot(X,(A-Y).T))
    b = b - lr*(1/m*np.sum(A-Y))
print("w:",w)
print("b:",b)

w: [[-0.64718517]
 [ 2.77465844]
 [ 0.04028756]]
b: [[-5.97503672]]

## 3 Comparing The Above Model With A scikit-learn Model

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
logreg = LogisticRegression('none')
logreg.fit(X.T,Y.T)

/home/allen/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(penalty='none')

In [14]:
print("w:",logreg.coef_.T)
print("b:",logreg.intercept_.reshape(1,1))

w: [[-0.64675267]
 [ 2.7746882 ]
 [ 0.04046201]]
b: [[-5.97523846]]

## 4 Conclusion
Similar values of the logistic regression parameters from 2 & 3 indicate that the custom gradient descent implementation is correct.